"""add form_responses table

Revision ID: 9a77f189d752
Revises: 214c6a750fab
Create Date: 2025-10-28 10:56:27.309682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a77f189d752'
down_revision: Union[str, Sequence[str], None] = '214c6a750fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('area_type', sa.String(), nullable=False),
    sa.Column('soil_type', sa.String(), nullable=False),
    sa.Column('water_source', sa.String(), nullable=False),
    sa.Column('irrigation', sa.String(), nullable=False),
    sa.Column('temperature', sa.String(), nullable=False),
    sa.Column('rainfall', sa.String(), nullable=False),
    sa.Column('sunlight', sa.String(), nullable=False),
    sa.Column('land_size', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('crop_duration', sa.String(), nullable=False),
    sa.Column('specific_crop', sa.String(), nullable=True),
    sa.Column('fertilizers_preference', sa.String(), nullable=True),
    sa.Column('last_planted_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_id'), 'form_responses', ['id'], unique=False)
    op.create_foreign_key('fk_form_responses_user_id', 'form_responses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_responses_id'), table_name='form_responses')
    op.drop_table('form_responses')
    # ### end Alembic commands ###
